{% set version = "0.0.0" %}

package:
  name: holoclean
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/93/c7/ee8bdce8085426413ef01c910439fa118a44f96bf717ec596545c3899c9d/holoclean-{{ version }}.tar.gz
  sha256: 458d9d3826d9349e83fc86d1cd37dc238a20a35eb693da63470a9d669324a735

requirements:
  build:
    - python>=3.7
    - setuptools
    - numpy==1.15.3
  run:
    - python>=3.7
    - pytorch==0.4.1
    - python-Levenshtein==0.12.0
    - psycopg2==2.7.5
    - sqlalchemy==1.2.12
    - tqdm==4.15.0
    - scipy==1.1.0
    - numpy==1.15.3
    - pandas==0.23.4

test:
  source_files:
    - tests/*
  imports:
    - holoclean

about:
  home: https://github.com/HoloClean/holoclean-1
  license: Apache
  license_file: LICENSE
